name: practica-github-actions
on:
  push:
    branches:
      - main
jobs:
  linter_job:
    # El job s'executa en una màquina Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      # Pas 1: Descarregar el codi del repositori
      - name: Checkout code
        uses: actions/checkout@v3

      # Pas 2: Instal·lar les dependències del projecte
      - name: Install dependencies
        run: npm install

      # Pas 3: Executar el linter
      - name: Run linter
        run: npm run lint

cypress_job:
  runs-on: ubuntu-latest
  needs: linter_job
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      uses: cypress-io/github-action@v4
      with:
        runTests: true
        continue-on-fail: true

    - name: Save results
      run: echo "$(cat cypress/results.txt)" > result.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: result.txt

# deploy_job:
#   runs-on: ubuntu-latest
#   needs: cypress_job
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Deploy to Vercel
#       uses: amondnet/vercel-action@v20
#       with:
#         vercel-token: ${{ secrets.VERCEL_TOKEN }}
#         github-token: ${{ secrets.GITHUB_TOKEN }}

# notification_job:
#   runs-on: ubuntu-latest
#   needs: [linter_job, cypress_job, add_badge_job, deploy_job]
#   steps:
#     - name: Send email
#       uses: ./send-email-action
#       with:
#         to: ${{ secrets.EMAIL }}
#         subject: "Resultat del workflow"
#         body: |
#           S'ha realitzat un push en la branca main que ha provocat l'execució del workflow nom_repositori_workflow amb els següents resultats:
#           - linter_job: ${{ job.status.linter_job }}
#           - cypress_job: ${{ job.status.cypress_job }}
#           - add_badge_job: ${{ job.status.add_badge_job }}
#           - deploy_job: ${{ job.status.deploy_job }}