name: nodejs-blog-practica

# Se ejecuta cuando se hace push a la rama main
on:
  push:
    branches:
      - main

jobs:
  linter_job:
    # Se ejecuta en una máquina virtual de Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Descarga el contenido del repositorio en la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura la versión de Node.js que se usará
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Instala las dependencias definidas en package.json
      - name: Install dependencies
        run: npm install

      # Ejecuta el linter para verificar la sintaxis del código
      - name: Run Linter
        run: npm run lint

  cypress_job:
    # Indica que este job depende de que termine linter_job
    needs: linter_job
    runs-on: ubuntu-latest

    steps:
      # Descarga el contenido del repositorio en la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instala las dependencias definidas en package.json
      - name: Install dependencies
        run: npm install

      # Construimos la app Next antes de arrancarla
      - name: Build Next app
        run: npm run build

      # Ejecuta los tests de cypress
      - name: Run Cypress tests
        id: run_cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
          # Fuerza que si Cypress falla, la conclusión del step sea "failure"
          fail-on-run-failure: true
        # Permite que el workflow continúe incluso si hay fallos en los tests
        continue-on-error: true

      # Usa la conclusión del paso anterior y genera result.txt con success/failure
      - name: Save Cypress test results
        run: |
          if [ "${{ steps.run_cypress.conclusion }}" = "success" ]; then
            echo "success" > result.txt
          else
            echo "failure" > result.txt
          fi
          cat result.txt

      # Sube el archivo result.txt como artefacto
      - name: Upload Cypress results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-result
          path: result.txt